// flow-typed signature: f4ea924ed8ba3dbb90cf8fe35a7fa08a
// flow-typed version: <<STUB>>/simplewebrtc_v^3.0.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplewebrtc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplewebrtc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simplewebrtc/build' {
  declare module.exports: any;
}

declare module 'simplewebrtc/out/simplewebrtc-with-adapter.bundle' {
  declare module.exports: any;
}

declare module 'simplewebrtc/out/simplewebrtc.bundle' {
  declare module.exports: any;
}

declare module 'simplewebrtc/src/peer' {
  declare module.exports: any;
}

declare module 'simplewebrtc/src/simplewebrtc' {
  declare module.exports: any;
}

declare module 'simplewebrtc/src/socketioconnection' {
  declare module.exports: any;
}

declare module 'simplewebrtc/src/webrtc' {
  declare module.exports: any;
}

declare module 'simplewebrtc/test/selenium/index' {
  declare module.exports: any;
}

declare module 'simplewebrtc/test/selenium/p2p' {
  declare module.exports: any;
}

declare module 'simplewebrtc/test/selenium/three' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simplewebrtc/build.js' {
  declare module.exports: $Exports<'simplewebrtc/build'>;
}
declare module 'simplewebrtc/out/simplewebrtc-with-adapter.bundle.js' {
  declare module.exports: $Exports<'simplewebrtc/out/simplewebrtc-with-adapter.bundle'>;
}
declare module 'simplewebrtc/out/simplewebrtc.bundle.js' {
  declare module.exports: $Exports<'simplewebrtc/out/simplewebrtc.bundle'>;
}
declare module 'simplewebrtc/src/peer.js' {
  declare module.exports: $Exports<'simplewebrtc/src/peer'>;
}
declare module 'simplewebrtc/src/simplewebrtc.js' {
  declare module.exports: $Exports<'simplewebrtc/src/simplewebrtc'>;
}
declare module 'simplewebrtc/src/socketioconnection.js' {
  declare module.exports: $Exports<'simplewebrtc/src/socketioconnection'>;
}
declare module 'simplewebrtc/src/webrtc.js' {
  declare module.exports: $Exports<'simplewebrtc/src/webrtc'>;
}
declare module 'simplewebrtc/test/selenium/index.js' {
  declare module.exports: $Exports<'simplewebrtc/test/selenium/index'>;
}
declare module 'simplewebrtc/test/selenium/p2p.js' {
  declare module.exports: $Exports<'simplewebrtc/test/selenium/p2p'>;
}
declare module 'simplewebrtc/test/selenium/three.js' {
  declare module.exports: $Exports<'simplewebrtc/test/selenium/three'>;
}
