// flow-typed signature: 64dfb23a505afb6c57df9387894d6888
// flow-typed version: <<STUB>>/webrtc-adapter_v^7.2.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webrtc-adapter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webrtc-adapter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webrtc-adapter/dist/adapter_core' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/adapter_core5' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/adapter_factory' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/chrome/chrome_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/chrome/getdisplaymedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/chrome/getusermedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/common_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/edge/edge_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/edge/filtericeservers' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/edge/getdisplaymedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/edge/getusermedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/firefox/firefox_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/firefox/getdisplaymedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/firefox/getusermedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/safari/safari_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/dist/utils' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/Gruntfile' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/out/adapter_no_edge_no_global' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/out/adapter_no_edge' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/out/adapter_no_global' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/out/adapter' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/adapter_core' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/adapter_core5' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/adapter_factory' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/chrome/chrome_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/chrome/getdisplaymedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/chrome/getusermedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/common_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/edge/edge_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/edge/filtericeservers' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/edge/getdisplaymedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/edge/getusermedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/firefox/firefox_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/firefox/getdisplaymedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/firefox/getusermedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/safari/safari_shim' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/src/js/utils' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/addIceCandidate' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/addTrack' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/browserdetails' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/connection' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/dtmf' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/getStats' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/getusermedia' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/maxMessageSize' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/mediaDevices' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/mediastream' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/msid' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/negotiationneeded' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/ontrack' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/removeTrack' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/rtcicecandidate' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/rtcpeerconnection' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/rtcsessiondescription' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/e2e/srcobject' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/getusermedia-mocha' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/karma.conf' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/adapter_factory' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/chrome' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/detectBrowser' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/edge' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/extractVersion' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/firefox' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/logSuppression' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/rtcicecandidate' {
  declare module.exports: any;
}

declare module 'webrtc-adapter/test/unit/safari' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webrtc-adapter/dist/adapter_core.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/adapter_core'>;
}
declare module 'webrtc-adapter/dist/adapter_core5.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/adapter_core5'>;
}
declare module 'webrtc-adapter/dist/adapter_factory.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/adapter_factory'>;
}
declare module 'webrtc-adapter/dist/chrome/chrome_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/chrome/chrome_shim'>;
}
declare module 'webrtc-adapter/dist/chrome/getdisplaymedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/chrome/getdisplaymedia'>;
}
declare module 'webrtc-adapter/dist/chrome/getusermedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/chrome/getusermedia'>;
}
declare module 'webrtc-adapter/dist/common_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/common_shim'>;
}
declare module 'webrtc-adapter/dist/edge/edge_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/edge/edge_shim'>;
}
declare module 'webrtc-adapter/dist/edge/filtericeservers.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/edge/filtericeservers'>;
}
declare module 'webrtc-adapter/dist/edge/getdisplaymedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/edge/getdisplaymedia'>;
}
declare module 'webrtc-adapter/dist/edge/getusermedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/edge/getusermedia'>;
}
declare module 'webrtc-adapter/dist/firefox/firefox_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/firefox/firefox_shim'>;
}
declare module 'webrtc-adapter/dist/firefox/getdisplaymedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/firefox/getdisplaymedia'>;
}
declare module 'webrtc-adapter/dist/firefox/getusermedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/firefox/getusermedia'>;
}
declare module 'webrtc-adapter/dist/safari/safari_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/safari/safari_shim'>;
}
declare module 'webrtc-adapter/dist/utils.js' {
  declare module.exports: $Exports<'webrtc-adapter/dist/utils'>;
}
declare module 'webrtc-adapter/Gruntfile.js' {
  declare module.exports: $Exports<'webrtc-adapter/Gruntfile'>;
}
declare module 'webrtc-adapter/out/adapter_no_edge_no_global.js' {
  declare module.exports: $Exports<'webrtc-adapter/out/adapter_no_edge_no_global'>;
}
declare module 'webrtc-adapter/out/adapter_no_edge.js' {
  declare module.exports: $Exports<'webrtc-adapter/out/adapter_no_edge'>;
}
declare module 'webrtc-adapter/out/adapter_no_global.js' {
  declare module.exports: $Exports<'webrtc-adapter/out/adapter_no_global'>;
}
declare module 'webrtc-adapter/out/adapter.js' {
  declare module.exports: $Exports<'webrtc-adapter/out/adapter'>;
}
declare module 'webrtc-adapter/src/js/adapter_core.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/adapter_core'>;
}
declare module 'webrtc-adapter/src/js/adapter_core5.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/adapter_core5'>;
}
declare module 'webrtc-adapter/src/js/adapter_factory.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/adapter_factory'>;
}
declare module 'webrtc-adapter/src/js/chrome/chrome_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/chrome/chrome_shim'>;
}
declare module 'webrtc-adapter/src/js/chrome/getdisplaymedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/chrome/getdisplaymedia'>;
}
declare module 'webrtc-adapter/src/js/chrome/getusermedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/chrome/getusermedia'>;
}
declare module 'webrtc-adapter/src/js/common_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/common_shim'>;
}
declare module 'webrtc-adapter/src/js/edge/edge_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/edge/edge_shim'>;
}
declare module 'webrtc-adapter/src/js/edge/filtericeservers.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/edge/filtericeservers'>;
}
declare module 'webrtc-adapter/src/js/edge/getdisplaymedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/edge/getdisplaymedia'>;
}
declare module 'webrtc-adapter/src/js/edge/getusermedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/edge/getusermedia'>;
}
declare module 'webrtc-adapter/src/js/firefox/firefox_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/firefox/firefox_shim'>;
}
declare module 'webrtc-adapter/src/js/firefox/getdisplaymedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/firefox/getdisplaymedia'>;
}
declare module 'webrtc-adapter/src/js/firefox/getusermedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/firefox/getusermedia'>;
}
declare module 'webrtc-adapter/src/js/safari/safari_shim.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/safari/safari_shim'>;
}
declare module 'webrtc-adapter/src/js/utils.js' {
  declare module.exports: $Exports<'webrtc-adapter/src/js/utils'>;
}
declare module 'webrtc-adapter/test/e2e/addIceCandidate.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/addIceCandidate'>;
}
declare module 'webrtc-adapter/test/e2e/addTrack.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/addTrack'>;
}
declare module 'webrtc-adapter/test/e2e/browserdetails.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/browserdetails'>;
}
declare module 'webrtc-adapter/test/e2e/connection.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/connection'>;
}
declare module 'webrtc-adapter/test/e2e/dtmf.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/dtmf'>;
}
declare module 'webrtc-adapter/test/e2e/getStats.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/getStats'>;
}
declare module 'webrtc-adapter/test/e2e/getusermedia.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/getusermedia'>;
}
declare module 'webrtc-adapter/test/e2e/maxMessageSize.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/maxMessageSize'>;
}
declare module 'webrtc-adapter/test/e2e/mediaDevices.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/mediaDevices'>;
}
declare module 'webrtc-adapter/test/e2e/mediastream.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/mediastream'>;
}
declare module 'webrtc-adapter/test/e2e/msid.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/msid'>;
}
declare module 'webrtc-adapter/test/e2e/negotiationneeded.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/negotiationneeded'>;
}
declare module 'webrtc-adapter/test/e2e/ontrack.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/ontrack'>;
}
declare module 'webrtc-adapter/test/e2e/removeTrack.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/removeTrack'>;
}
declare module 'webrtc-adapter/test/e2e/rtcicecandidate.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/rtcicecandidate'>;
}
declare module 'webrtc-adapter/test/e2e/rtcpeerconnection.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/rtcpeerconnection'>;
}
declare module 'webrtc-adapter/test/e2e/rtcsessiondescription.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/rtcsessiondescription'>;
}
declare module 'webrtc-adapter/test/e2e/srcobject.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/e2e/srcobject'>;
}
declare module 'webrtc-adapter/test/getusermedia-mocha.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/getusermedia-mocha'>;
}
declare module 'webrtc-adapter/test/karma.conf.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/karma.conf'>;
}
declare module 'webrtc-adapter/test/unit/adapter_factory.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/adapter_factory'>;
}
declare module 'webrtc-adapter/test/unit/chrome.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/chrome'>;
}
declare module 'webrtc-adapter/test/unit/detectBrowser.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/detectBrowser'>;
}
declare module 'webrtc-adapter/test/unit/edge.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/edge'>;
}
declare module 'webrtc-adapter/test/unit/extractVersion.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/extractVersion'>;
}
declare module 'webrtc-adapter/test/unit/firefox.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/firefox'>;
}
declare module 'webrtc-adapter/test/unit/logSuppression.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/logSuppression'>;
}
declare module 'webrtc-adapter/test/unit/rtcicecandidate.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/rtcicecandidate'>;
}
declare module 'webrtc-adapter/test/unit/safari.js' {
  declare module.exports: $Exports<'webrtc-adapter/test/unit/safari'>;
}
